seed: 42
train_questions_json: ../dataset/v2_OpenEnded_mscoco_train2014_questions.json
train_annotations_json: ../dataset/v2_mscoco_train2014_annotations.json
val_questions_json: ../dataset/v2_OpenEnded_mscoco_val2014_questions.json
val_annotations_json: ../dataset/v2_mscoco_val2014_annotations.json
train_images_dir: ../dataset/train2014
val_images_dir: ../dataset/val2014
train_image_filename_template: "COCO_train2014_{image_id:012d}.jpg"
val_image_filename_template: "COCO_val2014_{image_id:012d}.jpg"
captioner_project_root: ../SimpleImageCaptioner
captioner_ckpt: ../SimpleImageCaptioner/outputs/smoke/best.pt
captioner_class: SimpleImageCaptioner
num_workers: 0
batch_size: 4
grad_accum_steps: 1
epochs: 3
learning_rate: 0.0005
lr_decay_every: 4
lr_decay_factor: 0.6
max_question_len: 14
max_answer_len: 6
vocab_min_freq: 4
use_amp: true
max_regions: 16
cache_regions: true
region_cache_dir: outputs/region_cache/vqa_k32_d512
image_size: 224
device: cuda
ddp: false
ddp_backend: nccl
hidden_dim: 512
word_dim: 512
question_dim: 1280
fuse_mode: mul
save_dir: outputs/smoke
max_train_qids: 500
max_val_qids: 50
