seed: 42
dataset_root: ../dataset
num_workers: 2
prefetch_factor: 2
pin_memory: true
persistent_workers: true
batch_size: 4
grad_accum_steps: 4
epochs: 25
learning_rate: 0.0005
lr_decay_every: 4
lr_decay_factor: 0.6
weight_decay: 0.0
dropout: 0.5
max_question_len: 14
max_caption_len: 20
vocab_min_freq: 4
use_amp: true
max_regions: 32
device: cuda
hidden_dim: 512
word_dim: 512
question_dim: 1280
save_dir: outputs
