seed: 42
train_captions_json: ../dataset/captions_val2014.json
val_captions_json: ../dataset/captions_val2014.json
train_images_dir: ../dataset/val2014
val_images_dir: ../dataset/val2014
train_image_filename_template: "COCO_val2014_{image_id:012d}.jpg"
val_image_filename_template: "COCO_val2014_{image_id:012d}.jpg"
max_train_images: 10
max_val_images: 10
num_workers: 0
prefetch_factor: 2
pin_memory: false
persistent_workers: false
batch_size: 2
grad_accum_steps: 1
epochs: 1
learning_rate: 0.0005
lr_decay_every: 4
lr_decay_factor: 0.6
weight_decay: 0.0
dropout: 0.5
max_question_len: 14
max_caption_len: 20
vocab_min_freq: 1
use_amp: true
max_regions: 32
device: cuda
hidden_dim: 512
word_dim: 512
question_dim: 1280
save_dir: outputs/smoke
